# Generated by Django 3.2.5 on 2021-07-15 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concert_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
